name: 'PIP'
on:
  issues:
    types: [opened, reopened, edited]
env:
  TRUSTED_SENDERS:
    - gronke-bot
  TRUSTED_REPOS:
    - gronke/py-freebsd_sysctl
  TRUSTED_TEST_REPOS:
    - bsdci/py-freebsd_sysctl
jobs:
  publish:
    steps:
    - name: "Check Trusted Sender"
      if: contains(env.TRUSTED_SENDERS.*, .refgithub.event.sender.login) == false
      run: |
        echo "{ github.event.sender.login } is untrusted."
        exit 1
    - name: "Read Issue Body"
      id: issue_body
      run: |
        REPOSITORY=$(python3 -c "print(re.match(r'.*\nRepository: (.*?)\n.*', '${{ github.event.issue.comment.body }}', re.DOTALL)[1])')
        VERSION=$(python3 -c "print(re.match(r'.*\Version: ([0-9]+\.[0-9]+\.[0-9]+)\n.*', '${{ github.event.issue.comment.body }}', re.DOTALL)[1])')
        COMMIT=$(python3 -c "print(re.match(r'.*\Commit: ([0-9]+\.[0-9]+\.[0-9]+)\n.*', '${{ github.event.issue.comment.body }}', re.DOTALL)[1])')
        echo "::set-output name=REPOSITORY::$REPOSITORY"
        echo "::set-output name=VERSION::$VERSION"
        echo "::set-output name=COMMIT::$COMMIT"
    - name: "Install Tools"
      run: |
        python3 -m pip install -U pip
        python3 -m pip install twine
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: ${{ steps.issue_body.outputs.REPOSITORY }}
    - name: "Verify Repository"
      run: |
        CURRENT_COMMIT="$(git rev-parse --verify HEAD)"
        if [ "$CURRENT_COMMIT" != "${{ steps.issue_body.outputs.COMMIT }}" ]; then
          echo "Commit mismatch: (requested ${{ steps.issue_body.outputs.COMMIT }}, but found $CURRENT_COMMIT"
          exit 1
        fi
        if [ $(< VERSION) != "${{ steps.issue_body.outputs.REPOSITORY }}" ]; then
          echo "Version mismatch."
        fi
    - name: Bundle Package
      run: python setup.py sdist
    - name: "Deploy Package"
      if: contains(env.TRUSTED_REPOS.*, steps.issue_body.outputs.REPOSITORY)
      env:
        TWINE_PASSWORD: "${{ secrets.TESTPYPI_API_TOKEN }}"
      run: |
        echo "Deploying TRUSTED repository"
        ls -al
        echo ${{ github.event.issue.comment.body }}
        echo "dist/$(python3 setup.py --name)-$(python3 setup.py --version).tar.gz"
        ls -al dist/
    - name: "Deploy Package (Testing)"
      if: contains(env.TRUSTED_TEST_REPOS.*, steps.issue_body.outputs.REPOSITORY)
      env:
        TWINE_REPOSITORY_URL: "https://test.pypi.org/simple/"
        TWINE_PASSWORD: "${{ secrets.TESTPYPI_API_TOKEN }}"
      run: |
        echo "Deploying TEST repository"
        ls -al
        echo ${{ github.event.issue.comment.body }}
        echo "dist/$(python3 setup.py --name)-$(python3 setup.py --version).tar.gz"
        ls -al dist/
        python3 -m twine upload --non-interactive -u __token__ "dist/$(python3 setup.py --name)-$(python3 setup.py --version).tar.gz"
